/**
 * GeoResilience AI - Master Datasets with Vulnerability Fingerprint & Destination Infrastructure
 */
export const disasterData = {
  wayanad: {
    id: "wayanad",
    name: "Wayanad (Meppadi - Chooralmala Basin), Kerala",
    center: [11.5325, 76.1362],
    zoom: 13,
    geologicalContext: "High-gradient Western Ghats escarpment with thick laterite soil on fractured gneiss bedrock.",
    
    zones: [
      {
        id: "WZ-01",
        name: "Chooralmala Upper Escarpment",
        baseSlope: 42,
        soilType: "Laterite Clayey (2.8m)",
        soilThickness: 2.8,
        drainageDistance: 45,
        floodRisk: 78,
        landslideRisk: 94,
        cloudburstRisk: 88,
        disasterHistoryScore: 92,
        coordinates: [
          [11.542, 76.128],
          [11.549, 76.135],
          [11.541, 76.148],
          [11.533, 76.138],
        ],
      },
      {
        id: "WZ-02",
        name: "Mundakkai Valley Basin",
        baseSlope: 36,
        soilType: "Gravelly Sandy Loam (3.2m)",
        soilThickness: 3.2,
        drainageDistance: 20,
        floodRisk: 92,
        landslideRisk: 86,
        cloudburstRisk: 82,
        disasterHistoryScore: 89,
        coordinates: [
          [11.533, 76.138],
          [11.541, 76.148],
          [11.530, 76.160],
          [11.522, 76.147],
        ],
      },
      {
        id: "WZ-03",
        name: "Attamala Hill Settlement Spur",
        baseSlope: 28,
        soilType: "Sandy Clay with Boulders (2.1m)",
        soilThickness: 2.1,
        drainageDistance: 120,
        floodRisk: 45,
        landslideRisk: 68,
        cloudburstRisk: 70,
        disasterHistoryScore: 65,
        coordinates: [
          [11.522, 76.147],
          [11.530, 76.160],
          [11.515, 76.168],
          [11.508, 76.152],
        ],
      },
      {
        id: "WZ-04",
        name: "Meppadi Foothills & Plateau (Safe Green Hub)",
        baseSlope: 9,
        soilType: "Compacted Red Soil on Stable Bedrock",
        soilThickness: 1.2,
        drainageDistance: 450,
        floodRisk: 15,
        landslideRisk: 12,
        cloudburstRisk: 25,
        disasterHistoryScore: 10,
        coordinates: [
          [11.545, 76.110],
          [11.560, 76.128],
          [11.542, 76.128],
          [11.525, 76.115],
        ],
      },
      {
        id: "WZ-05",
        name: "Kalpetta Ridge Green Sanctuary",
        baseSlope: 6,
        soilType: "Hard Charnockite Bedrock",
        soilThickness: 0.8,
        drainageDistance: 600,
        floodRisk: 8,
        landslideRisk: 6,
        cloudburstRisk: 18,
        disasterHistoryScore: 5,
        coordinates: [
          [11.555, 76.085],
          [11.575, 76.110],
          [11.560, 76.128],
          [11.540, 76.095],
        ],
      },
    ],

    // Rich Vulnerability Fingerprint per Habitation
    habitations: [
      {
        id: "HAB-104",
        name: "Punchirimattam Ridge Hamlet",
        zoneId: "WZ-01",
        coordinates: [11.546, 76.132],
        population: 310,
        households: 72,
        fingerprint: {
          elderly: 78,
          infants: 52,
          disabilities: 24,
          medicalDependency: "High (Dialysis & Chronic)",
          structuralFragility: 0.94, // 94% Kutcha / Tin structures
          accessCutoffRisk: 0.95,     // Single narrow unpaved footpath
          disasterHistory: "Severe (2019 Debris Flow)",
          socioEconomicResilience: "Low (Daily Wage Tea Labor)",
        },
      },
      {
        id: "HAB-101",
        name: "Mundakkai Tea Plantation Colony",
        zoneId: "WZ-02",
        coordinates: [11.532, 76.145],
        population: 840,
        households: 195,
        fingerprint: {
          elderly: 185,
          infants: 135,
          disabilities: 48,
          medicalDependency: "High",
          structuralFragility: 0.88,
          accessCutoffRisk: 0.90, // Stream bridge dependent
          disasterHistory: "Severe (2020 Flash Flood)",
          socioEconomicResilience: "Low",
        },
      },
      {
        id: "HAB-102",
        name: "Chooralmala Bazaar & Quarters",
        zoneId: "WZ-01",
        coordinates: [11.538, 76.135],
        population: 1420,
        households: 330,
        fingerprint: {
          elderly: 260,
          infants: 195,
          disabilities: 55,
          medicalDependency: "Medium",
          structuralFragility: 0.76,
          accessCutoffRisk: 0.85, // Bridge dependent
          disasterHistory: "Severe",
          socioEconomicResilience: "Medium",
        },
      },
      {
        id: "HAB-103",
        name: "Attamala Upper Enclave",
        zoneId: "WZ-03",
        coordinates: [11.518, 76.155],
        population: 460,
        households: 110,
        fingerprint: {
          elderly: 82,
          infants: 48,
          disabilities: 18,
          medicalDependency: "Low",
          structuralFragility: 0.62,
          accessCutoffRisk: 0.70,
          disasterHistory: "Moderate",
          socioEconomicResilience: "Medium",
        },
      },
      {
        id: "HAB-105",
        name: "Meppadi South Residential Sector",
        zoneId: "WZ-04",
        coordinates: [11.548, 76.120],
        population: 2650,
        households: 620,
        fingerprint: {
          elderly: 310,
          infants: 170,
          disabilities: 35,
          medicalDependency: "Low",
          structuralFragility: 0.20,
          accessCutoffRisk: 0.15,
          disasterHistory: "Low",
          socioEconomicResilience: "High",
        },
      },
    ],

    // Multi-Dimensional Relocation Destination Sites (Carrying Capacity)
    relocationSites: [
      {
        id: "SITE-01",
        name: "Meppadi Central Transit Hub",
        coordinates: [11.552, 76.122],
        maxCapacity: 1500,
        currentOccupancy: 450,
        availableHeadroom: 1050, // 1500 - 450 = 1050
        suitability: {
          hazardSafety: 94,
          drinkingWater: 92, // 45 LPCD verified
          sanitationPiped: 88,
          healthcareProximity: 90, // Primary Health Center 300m
          roadConnectivity: 95,    // 2-Lane Highway
          schoolCapacity: 80,
          overallScore: 90,
        },
        status: "ACTIVE",
      },
      {
        id: "SITE-02",
        name: "Kalpetta Greenfield Stadium Sanctuary",
        coordinates: [11.565, 76.098],
        maxCapacity: 4500,
        currentOccupancy: 800,
        availableHeadroom: 3700,
        suitability: {
          hazardSafety: 98,
          drinkingWater: 96,
          sanitationPiped: 94,
          healthcareProximity: 95, // District General Hospital 1.2km
          roadConnectivity: 98,    // 4-Lane State Highway
          schoolCapacity: 92,
          overallScore: 96,
        },
        status: "ACTIVE",
      },
      {
        id: "SITE-03",
        name: "St. Joseph Hill Community Camp",
        coordinates: [11.545, 76.115],
        maxCapacity: 1200,
        currentOccupancy: 300,
        availableHeadroom: 900,
        suitability: {
          hazardSafety: 92,
          drinkingWater: 72,
          sanitationPiped: 68,
          healthcareProximity: 60,
          roadConnectivity: 75,
          schoolCapacity: 65,
          overallScore: 74,
        },
        status: "ACTIVE",
      },
    ],

    evacuationRoutes: [
      {
        fromHabitationId: "HAB-104",
        toSiteId: "SITE-01",
        distanceKm: 4.8,
        transitMinutes: 18,
        safetyRating: "96% Hazard Bypassed (Upper Ridge Corridor)",
        waypoints: [
          [11.546, 76.132],
          [11.543, 76.129],
          [11.548, 76.124],
          [11.552, 76.122],
        ],
      },
      {
        fromHabitationId: "HAB-101",
        toSiteId: "SITE-03",
        distanceKm: 5.6,
        transitMinutes: 22,
        safetyRating: "94% Elevated Stream Bypass",
        waypoints: [
          [11.532, 76.145],
          [11.530, 76.138],
          [11.538, 76.125],
          [11.545, 76.115],
        ],
      },
      {
        fromHabitationId: "HAB-102",
        toSiteId: "SITE-01",
        distanceKm: 3.2,
        transitMinutes: 12,
        safetyRating: "98% High Ground Clearance",
        waypoints: [
          [11.538, 76.135],
          [11.542, 76.128],
          [11.548, 76.124],
          [11.552, 76.122],
        ],
      },
      {
        fromHabitationId: "HAB-103",
        toSiteId: "SITE-03",
        distanceKm: 6.4,
        transitMinutes: 26,
        safetyRating: "92% Ridge Line Road",
        waypoints: [
          [11.518, 76.155],
          [11.524, 76.140],
          [11.535, 76.125],
          [11.545, 76.115],
        ],
      },
    ],
  },

  joshimath: {
    id: "joshimath",
    name: "Joshimath Urban Catchment, Chamoli, Uttarakhand",
    center: [30.556, 79.567],
    zoom: 14,
    geologicalContext: "Glacial moraine debris slope experiencing severe toe erosion and deep subsurface subsidence.",

    zones: [
      {
        id: "JZ-01",
        name: "Sunil / Manohar Bagh Subsidence Core",
        baseSlope: 34,
        soilType: "Glacial Moraine Debris (4.5m)",
        soilThickness: 4.5,
        drainageDistance: 90,
        floodRisk: 30,
        landslideRisk: 96,
        cloudburstRisk: 75,
        disasterHistoryScore: 95,
        coordinates: [
          [30.562, 79.560],
          [30.568, 79.569],
          [30.559, 79.575],
          [30.552, 79.564],
        ],
      },
      {
        id: "JZ-02",
        name: "Marwari River Toe Slopes",
        baseSlope: 40,
        soilType: "Fractured Colluvium (3.8m)",
        soilThickness: 3.8,
        drainageDistance: 15,
        floodRisk: 88,
        landslideRisk: 92,
        cloudburstRisk: 80,
        disasterHistoryScore: 90,
        coordinates: [
          [30.552, 79.564],
          [30.559, 79.575],
          [30.548, 79.582],
          [30.541, 79.570],
        ],
      },
      {
        id: "JZ-03",
        name: "Auli Foothills Stable Bedrock Spur (Green Hub)",
        baseSlope: 11,
        soilType: "Hard Granite-Gneiss Bedrock",
        soilThickness: 0.9,
        drainageDistance: 550,
        floodRisk: 10,
        landslideRisk: 15,
        cloudburstRisk: 30,
        disasterHistoryScore: 8,
        coordinates: [
          [30.540, 79.545],
          [30.555, 79.558],
          [30.545, 79.565],
          [30.530, 79.550],
        ],
      },
    ],

    habitations: [
      {
        id: "JH-201",
        name: "Manohar Bagh Settlement",
        zoneId: "JZ-01",
        coordinates: [30.561, 79.567],
        population: 920,
        households: 210,
        fingerprint: {
          elderly: 210,
          infants: 120,
          disabilities: 38,
          medicalDependency: "High",
          structuralFragility: 0.96, // Active wide fissures
          accessCutoffRisk: 0.88,
          disasterHistory: "Severe (2023 Subsidence)",
          socioEconomicResilience: "Low",
        },
      },
      {
        id: "JH-202",
        name: "Sunil Village Ward #7",
        zoneId: "JZ-01",
        coordinates: [30.565, 79.563],
        population: 680,
        households: 155,
        fingerprint: {
          elderly: 145,
          infants: 85,
          disabilities: 26,
          medicalDependency: "Medium",
          structuralFragility: 0.90,
          accessCutoffRisk: 0.82,
          disasterHistory: "Severe",
          socioEconomicResilience: "Medium",
        },
      },
      {
        id: "JH-203",
        name: "Marwari Municipal Colony",
        zoneId: "JZ-02",
        coordinates: [30.549, 79.572],
        population: 1150,
        households: 260,
        fingerprint: {
          elderly: 195,
          infants: 140,
          disabilities: 32,
          medicalDependency: "Low",
          structuralFragility: 0.84,
          accessCutoffRisk: 0.78,
          disasterHistory: "High",
          socioEconomicResilience: "Medium",
        },
      },
    ],

    relocationSites: [
      {
        id: "JSITE-01",
        name: "Pipalkoti Central Relief Town",
        coordinates: [30.538, 79.548],
        maxCapacity: 4000,
        currentOccupancy: 600,
        availableHeadroom: 3400,
        suitability: {
          hazardSafety: 96,
          drinkingWater: 94,
          sanitationPiped: 92,
          healthcareProximity: 90, // Sub-District Hospital
          roadConnectivity: 96,    // NH-07 Highway
          schoolCapacity: 88,
          overallScore: 94,
        },
        status: "ACTIVE",
      },
      {
        id: "JSITE-02",
        name: "Auli Alpine Tourism Transit Camp",
        coordinates: [30.546, 79.556],
        maxCapacity: 2000,
        currentOccupancy: 400,
        availableHeadroom: 1600,
        suitability: {
          hazardSafety: 92,
          drinkingWater: 80,
          sanitationPiped: 75,
          healthcareProximity: 85, // Army Base Hospital
          roadConnectivity: 70,    // Winding Hill Pass
          schoolCapacity: 60,
          overallScore: 80,
        },
        status: "ACTIVE",
      },
    ],

    evacuationRoutes: [
      {
        fromHabitationId: "JH-201",
        toSiteId: "JSITE-01",
        distanceKm: 4.2,
        transitMinutes: 16,
        safetyRating: "97% Bedrock Highway",
        waypoints: [
          [30.561, 79.567],
          [30.555, 79.558],
          [30.546, 79.552],
          [30.538, 79.548],
        ],
      },
      {
        fromHabitationId: "JH-202",
        toSiteId: "JSITE-01",
        distanceKm: 5.1,
        transitMinutes: 20,
        safetyRating: "95% Stable Corridor",
        waypoints: [
          [30.565, 79.563],
          [30.558, 79.556],
          [30.546, 79.552],
          [30.538, 79.548],
        ],
      },
      {
        fromHabitationId: "JH-203",
        toSiteId: "JSITE-02",
        distanceKm: 3.5,
        transitMinutes: 14,
        safetyRating: "93% Elevated Ridge Route",
        waypoints: [
          [30.549, 79.572],
          [30.547, 79.562],
          [30.546, 79.556],
        ],
      },
    ],
  },
};
